### PR TITLE
handle run_constrained and constraints in run_exports

### PR DESCRIPTION
**Pull request by minrk**
follow-up to #30, this actually implements applications of constraints to the solve

### CODE REVIEW

**Comment by beckermr** [comment]
@jaimergp do you understand the solver errors here? I don't get the error that arrow-cpp does not exist.

**Comment by jaimergp** [comment]
Hm, I haven't used that method. What about `add_pin`? Would that work?

**Comment by beckermr** [comment]
I don't see why that makes sense. Care to explain more?

**Review by beckermr — CHANGES_REQUESTED** [review]
Adding pins as I understand them won't work. Sometimes people use run constraints to versions of packages that do not exist. I assume the solver will try to install the pins and this will create false negatives.

**Comment by minrk** [comment]
I opened https://github.com/mamba-org/mamba/issues/3293 because `add_constraint` seems to add the package to the install specs. I think `add_pin` works, and I added a test to ensure that constraints don't get added to the solution. Maybe I misunderstood what `add_constraint` means.

**Comment by beckermr** [comment]
Ohhhhh wow. I think add_pin <-> add_constraint need to have their names swapped. If add_pin does not install, then we're fine.

**Comment by minrk** [comment]
@beckermr I don't know if it's a terminology problem or what, but that's what I expected, too. But it's not how it behaves, despite [explicitly stating it should, I think](https://github.com/mamba-org/mamba/blob/9006fb963beaaa94014ee2d86b90355c4876bd95/libmamba/ext/solv-cpp/include/solv-cpp/solvable.hpp#L324-L326). `add_constraint` adds the package to the install list, while `add_pin` only constrains the version and works whether it's installed or not. `add_pin` required `installed_repo` to be set, which I also don't understand, but 🤷 it seems to have the effect I expected constraint to have.

**Comment by beckermr** [comment]
If this passes, I think we'll want a tighter pin on libmambapy in the feedstock so that if this bug gets fixed, things still work.

**Comment by minrk** [comment]
2.0 is in beta already which appears to [significantly change the Python API](https://mamba.readthedocs.io/en/latest/developer_zone/changes-2.0.html#libmambapy-python-bindings), so `<2` might be enough.

**Comment by beckermr** [comment]
We'll need to patch old release of this anyways then.

**Comment by minrk** [comment]
I added a few tests that run in a matter of seconds for me, but CI runtime has more than doubled in this PR. I don't know if that's a fluke or a consequence of the pinning changes.

**Comment by beckermr** [comment]
It is probably related, but TBH we don't get a choice on these things. The solver takes how long the solver takes. I am going to merge and we can add options to turn this off later if we need it.

**Pull request merged**
