### PR TITLE
feat: solvability implementation for rattler-build

### PR DESCRIPTION
**Pull request by wolfv**

### CODE REVIEW

**Comment by wolfv** [comment]
Alright, this works! :) Will have to come up with some unsovlable ones for a test.

**Review by beckermr — CHANGES_REQUESTED** [review]
The `suppress_output()` context needs to be added back in the correct spots.

**Comment by wolfv** [comment]
I restored the output supression. I think from my end this doesn't really need more work.

**Review by beckermr — CHANGES_REQUESTED** [review]
Cool. A few more items. 

- The print statements need to be changed to print_debug

- we need a test with an unsolvable recipe that shows what the output looks like.

**Comment by wolfv** [comment]
The error looks something like:

```
osx_arm64_: Rattler build errors: ╭─ Finding outputs from recipe
 │ Found 1 variants
 │ Build variant: v1-unsolvable-0.1-py100hfde170a_0
 │ 
 │ ╭─────────────────┬───────────╮
 │ │ Variant         ┆ Version   │
 │ ╞═════════════════╪═══════════╡
 │ │ python          ┆ 100       │
 │ │ target_platform ┆ osx-arm64 │
 │ ╰─────────────────┴───────────╯
 │
 ╰─────────────────── (took 0 seconds)

 ╭─ Resolving environments
 │ 
 │ Resolving environment for:
 │   Platform: osx-arm64
 │   Channels: 
 │    - file:///Users/wolfv/Programs/conda-forge/conda-forge-feedstock-check-solvable/output/
 │    - file:///var/folders/ls/nd2_c1qn1tz8c8sccxmg83m00000gn/T/tmppirjyobl/
 │    - conda-forge
 │    - file:///var/folders/ls/nd2_c1qn1tz8c8sccxmg83m00000gn/T/tmppirjyobl/
 │   Specs:
 │    - python 100.*
 │
 ╰─────────────────── (took 0 seconds)
Error:   × Failed to resolve dependencies: Cannot solve the request because of: No candidates were found for python 100.*.
  │ 
  ╰─▶ Cannot solve the request because of: No candidates were found for python 100.*.
```

I think that should be fine - wdyt?

**Comment by wolfv** [comment]
Also removed print statements / replaced with `print_debug`.

**Review by beckermr — APPROVED** [review]

**Pull request merged**
